FORMAT: 1A

# IOTAL API
This is the api documentation for iotal app

# Group Offices

Resources related to offices in the API

## Question Collection [/offices]

### List All Offices [GET]

+ Response 200 (application/json)

  []
